name: CD to Standalone Docker Host

on:
  push:
    branches: [ "main" ] # Trigger deployment on pushes to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.10.0
      with:
        ssh-private-key: ${{ secrets.DEPLOYMENT_SSH_KEY }}

    - name: Install SSH client
      run: sudo apt-get update && sudo apt-get install -y openssh-client

    - name: Deploy to Docker Host
      run: |
        echo "Deploying to ${{ secrets.DEPLOYMENT_HOST }}"
        ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOYMENT_USER }}@${{ secrets.DEPLOYMENT_HOST }} << EOF
          echo "Connected to Docker host"
          cd ../../  # Replace with the actual path on your server
          echo "Stopping existing containers (if any)"
          docker-compose down
          echo "Pulling latest images"
          docker-compose pull
          echo "Starting containers"
          docker-compose up -d
          echo "Deployment complete"
        EOF

    - name: Deployment successful
      run: echo "Application deployed successfully!"
