name: Deploy Local Docker Host
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: sonal # Ensure this job runs on your self-hosted runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    #- name: Navigate to Docker Compose Directory
      #run: cd /path/to/your/docker-compose/directory # Replace with the actual path

    - name: Stop Existing Containers (if any)
      run: docker-compose down

    - name: Pull Latest Images
      run: docker-compose pull

    - name: Start Containers
      run: docker-compose up -d

    - name: Deployment successful
      run: echo "Application deployed successfully on the local Docker host!"
