name: Deploy Local Docker Host
on:
  workflow_dispatch:

jobs:
  linter:
    runs-on: self-hosted 
    steps:
    - name: Scan the Docker Files with Liner
      run: sudo hadolint 
    
  deploy:
    runs-on: self-hosted # Ensure this job runs on your self-hosted runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    #- name: Navigate to Docker Compose Directory
      #run: cd /path/to/your/docker-compose/directory # Replace with the actual path

    - name: Stop Existing Containers (if any)
      run: docker-compose down

    - name: Pull Latest Images
      run: docker-compose pull

    #- name: Install Docker Scout CLI
#      run: |
 #         curl -sSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh
  #        sudo mv ~/.docker/cli-plugins/docker-scout /usr/local/bin/

    - name: Scan Application UI
      run: sudo docker-scout cves mreferre/yelb-ui:0.10  # Replace with your actual image name and tag
      
    - name: Scan Application App Server
      run: sudo docker-scout cves mreferre/yelb-appserver:0.7  # Replace with your actual image name and tag
      
    - name: Scan Redis 
      run: sudo docker-scout cves redis:4.0.2 # Replace with your actual image name and tag
      
    - name: Scan Database
      run: sudo docker-scout cves mreferre/yelb-db:0.6  # Replace with your actual image name and tag
    
            
    - name: Start Containers
      run: docker-compose up -d

    - name: Deployment successful
      run: echo "Application deployed successfully on the local Docker host!"
      #
